### ISSUE TITLE
Feature request: tolerance for time differences

### ISSUE THREAD

**Issue by johanflikweert** [WebFlight/JWT#15]
In our project we receive tokens which have a nbf (not valid before) timestamp which lies a little bit in the future compared with the server time. Sometimes this rounds off to just the second in the future, which makes the token strictly seen invalid. Could a time tolerance be build in such that both nbf and exp timestamps are not handled so strict? Or do you think we should really synchronize our server time better?

**Comment by mennodehaas** [comment]
Hi @johanflikweert, thanks for your feedback! Small differences in server time can indeed occur. You can use the leeway parameter to allow for a time tolerance. Did you try that one?

**Comment by johanflikweert** [comment]
Hi Menno, Thanks for your quick reply. Sorry I did not read the release notes well enough. We were able to implement the leeway parameter in the project like you did (had to do it manually, as we are still in Mendix 7) and this solved the problem. Thanks!
