### ISSUE TITLE
Hardcoded expiration on public certificate

### ISSUE THREAD

**Issue by kmarcinkowski-objectivity** [WebFlight/JWT#19]
Hi, 
I would like to report that in `generatePublic` method of `RSAKeyPairGenerator` class there is a hardcoded certificate expiration date logic, and the method argument `validity` is unused.

This causes the generated Public cert to be always valid for 3 years since generation time, instead of how long the user defined.

[Link to method](https://github.com/WebFlight/JWT/blob/9df250557275f85ee2b1e55d3ef512d5e0c0b800/javasource/jwt/helpers/RSAKeyPairGenerator.java#L69C29-L69C29)

**Comment by JaapvanLeeuwen** [comment]
Sorry for the late reply, but this has been fixed (and released to mendix app store). Thanks for letting us know!
