### ISSUE TITLE
Handle arrays

### ISSUE THREAD

**Issue by robertprice** [WebFlight/JWT#7]
At the moment the importing of arrays is missing which can be a problem if we want to import a JWT with a list of roles.

A quick fix is to create an extra many to one association between a new PublicClaimArray entity and PublicClaim. This new entity has a single attribute "Value" that is a String.

In DecodedJWTParser.java an extra claim parser can be added to iterate an array and populate this entity.

``			if (claim.asArray(String.class) != null) {
				logger.debug("Parse claim " + value + " as Array claim");
				String[] resultArray = claim.asArray(String.class);
				for (String result : resultArray) {
					PublicClaimArray publicClaimArray = new PublicClaimArray(context);
					publicClaimArray.setPublicClaimArray_PublicClaim(publicClaimResponse);
					publicClaimArray.setValue(result);
				} 
			}

**Comment by mennodehaas** [comment]
Solved in release https://github.com/WebFlight/JWT/releases/tag/v3.2
